### ISSUE TITLE
Breaks under sass-loader 4.0.1

### ISSUE THREAD

**Issue by neverfox** [Updater/node-sass-json-importer#34]
```
var includePaths = this.options.includePaths ? this.options.includePaths.split(':') : [];
                         ^

TypeError: Cannot read property 'options' of undefined
    at exports.default (node_modules/node-sass-json-importer/dist/node-sass-json-importer.js:29:26)
    at Object.<anonymous> (node_modules/sass-loader/index.js:412:20)
    at options.importer.(anonymous function) (node_modules/node-sass/lib/index.js:324:32)
```

Worked under 4.0.0. The change centers around [this PR](https://github.com/jtangelder/sass-loader/pull/267).

**Comment by tsuyoshiwada** [comment]
I am also going on the same problem.

**Comment by neverfox** [comment]
I've submitted a PR to sass-loader to fix this.

**Comment by neverfox** [comment]
Closing since this isn't an issue with this project.
